using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Ghost;

[GenerateTypedNameReferences]
public sealed partial class GhostHudWindow : FancyWindow
{
    public event Action<GhostHudType, bool>? OnHudToggled;

    public GhostHudWindow()
    {
        RobustXamlLoader.Load(this);

        MedicalHud.OnToggled += args => OnHudToggled?.Invoke(GhostHudType.Medical, args.Pressed);
        SecurityHud.OnToggled += args => OnHudToggled?.Invoke(GhostHudType.Security, args.Pressed);
    }

    public void SetState(GhostHudBoundUserInterfaceState state)
    {
        MedicalHud.Pressed = state.MedicalEnabled;
        SecurityHud.Pressed = state.SecurityEnabled;
    }
}
