- type: job
  id: GhostRole
  playTimeTracker: JobGhostRole
  name: job-name-ghost-role
  description: job-description-ghost-role
  experienceDefinition: NoExperience
  setPreference: false
  canBeAntag: true
  dontUseNameForTitles: true
