// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared.SS220.CultYogg.FungusMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.SS220.CultYogg.FungusMachine;

[GenerateTypedNameReferences]
public sealed partial class FungusMachineMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IGameTiming _gameTiming = default!;

    private FungusMachineInterfaceState? _state;
    private string? _pendingCultureId;
    private int _displayedSeconds = -1;
    private int _displayedGrowthStage = -1;

    public event Action<string>? OnGrowRequested;
    public event Action? OnHarvestRequested;

    public FungusMachineMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GrowButton.OnPressed += _ => RequestGrow();
        HarvestButton.OnPressed += _ => OnHarvestRequested?.Invoke();
    }

    public void UpdateState(FungusMachineInterfaceState state)
    {
        if (_state == null ||
            !_state.Inventory.Select(entry => entry.Id).SequenceEqual(state.Inventory.Select(entry => entry.Id)))
            RebuildCatalog(state.Inventory);

        _state = state;

        if (GetEntry(_pendingCultureId) == null)
            _pendingCultureId = state.SelectedCultureId ?? state.Inventory.FirstOrDefault()?.Id;

        UpdateSelectionPanel();
        UpdateCurrentCulture(state);
    }

    private void RebuildCatalog(List<FungusMachineInventoryEntry> inventory)
    {
        FungusContents.DisposeAllChildren();

        var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        foreach (var entry in inventory)
        {
            if (!_prototypeManager.TryIndex<EntityPrototype>(entry.ProductId, out var productPrototype))
                continue;

            var button = new FungusCultureButton(entry, spriteSystem.GetPrototypeIcon(productPrototype).Default);
            button.OnPressed += _ => SelectCulture(button.CultureId);
            FungusContents.AddChild(button);
        }
    }

    private void SelectCulture(string cultureId)
    {
        _pendingCultureId = cultureId;
        UpdateSelectionPanel();
    }

    private void UpdateSelectionPanel()
    {
        var entry = GetEntry(_pendingCultureId);

        SelectedCultureName.Text = Loc.GetString(entry?.Name ?? "cult-yogg-fungus-ui-no-selection");
        SelectedCultureDescription.SetMessage(entry == null ? string.Empty : FormatGrowthDetails(entry));

        var replacesCulture = entry != null &&
                              _state?.SelectedCultureId != null &&
                              _state.SelectedCultureId != _pendingCultureId;
        ReplaceWarning.Visible = replacesCulture;
        GrowButton.Text = Loc.GetString(replacesCulture
            ? "cult-yogg-fungus-ui-replace"
            : "cult-yogg-fungus-ui-grow");
        GrowButton.Disabled = entry == null || _pendingCultureId == _state?.SelectedCultureId;

        foreach (FungusCultureButton button in FungusContents.Children)
        {
            button.Pressed = button.CultureId == _pendingCultureId;
            button.Disabled = button.CultureId == _state?.SelectedCultureId;
        }
    }

    private void UpdateCurrentCulture(FungusMachineInterfaceState state)
    {
        var current = GetEntry(state.SelectedCultureId);
        CurrentCultureName.Text = Loc.GetString(current?.Name ?? "cult-yogg-fungus-ui-empty");
        CurrentYield.Text = current == null
            ? string.Empty
            : Loc.GetString("cult-yogg-fungus-ui-yield", ("yield", state.Yield));
        HarvestButton.Disabled = current == null || !state.HarvestReady;
        RebuildGrowthStages(current?.GrowthStages ?? 0);

        if (current == null)
        {
            CurrentStatus.Text = Loc.GetString("cult-yogg-fungus-ui-select-culture");
            CurrentTiming.Text = string.Empty;
            return;
        }

        if (state.HarvestReady)
        {
            CurrentStatus.Text = Loc.GetString("cult-yogg-fungus-ui-ready");
            CurrentTiming.Text = Loc.GetString("cult-yogg-fungus-ui-ready-hint");
            UpdateGrowthStages(1);
            return;
        }

        CurrentStatus.Text = Loc.GetString("cult-yogg-fungus-ui-growing");
        _displayedSeconds = -1;
        UpdateCountdown();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        UpdateCountdown();
    }

    private void RebuildGrowthStages(int stageCount)
    {
        if (GrowthStages.ChildCount == stageCount)
            return;

        GrowthStages.DisposeAllChildren();
        _displayedGrowthStage = -1;

        for (var i = 0; i < stageCount; i++)
        {
            GrowthStages.AddChild(new PanelContainer
            {
                HorizontalExpand = true,
                StyleClasses = { StyleClass.PanelDark },
            });
        }
    }

    private void UpdateGrowthStages(double progress)
    {
        var activeStages = Math.Clamp((int) Math.Ceiling(progress * GrowthStages.ChildCount), 0, GrowthStages.ChildCount);

        if (_displayedGrowthStage == activeStages)
            return;

        _displayedGrowthStage = activeStages;
        for (var i = 0; i < GrowthStages.ChildCount; i++)
        {
            GrowthStages.GetChild(i).SetOnlyStyleClass(i < activeStages ? StyleClass.Positive : StyleClass.PanelDark);
        }
    }

    private void UpdateCountdown()
    {
        if (_state == null || _state.HarvestReady || GetEntry(_state.SelectedCultureId) == null)
            return;

        var secondsUntilHarvest = Math.Max(0, (_state.HarvestEndTime - _gameTiming.CurTime).TotalSeconds);
        UpdateGrowthStages(_state.HarvestDuration > TimeSpan.Zero
            ? 1 - secondsUntilHarvest / _state.HarvestDuration.TotalSeconds
            : 0);

        var displayedSeconds = (int) Math.Ceiling(secondsUntilHarvest);
        if (_displayedSeconds == displayedSeconds)
            return;

        _displayedSeconds = displayedSeconds;
        CurrentTiming.Text = Loc.GetString(
            "cult-yogg-fungus-ui-time-left",
            ("time", FormatTime(displayedSeconds)));
    }

    private void RequestGrow()
    {
        if (_pendingCultureId == null || _pendingCultureId == _state?.SelectedCultureId)
            return;

        OnGrowRequested?.Invoke(_pendingCultureId);
    }

    private FungusMachineInventoryEntry? GetEntry(string? id)
    {
        return id == null ? null : _state?.Inventory.FirstOrDefault(entry => entry.Id == id);
    }

    private static string FormatTime(int seconds)
    {
        var duration = TimeSpan.FromSeconds(seconds);
        return $"{(int) duration.TotalMinutes}:{duration.Seconds:00}";
    }

    private static string FormatGrowthDetails(FungusMachineInventoryEntry entry)
    {
        var repeatHarvest = entry.HarvestRepeats
            ? FormatTime(entry.RepeatHarvestSeconds)
            : Loc.GetString("cult-yogg-fungus-ui-no-repeat-harvest");

        return Loc.GetString(
            "cult-yogg-fungus-ui-growth-details",
            ("firstHarvest", FormatTime(entry.FirstHarvestSeconds)),
            ("repeatHarvest", repeatHarvest),
            ("stages", entry.GrowthStages),
            ("maturation", entry.MaturationCycles),
            ("production", entry.ProductionCycles),
            ("yield", entry.Yield));
    }
}
