// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using System.Numerics;
using Content.Shared.SS220.CultYogg.FungusMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.SS220.CultYogg.FungusMachine;

[GenerateTypedNameReferences]
public sealed partial class FungusMachineMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private static readonly StyleBoxFlat ActiveGrowthStageStyle = new()
    {
        BackgroundColor = Color.FromHex("#6f9e4f"),
        BorderColor = Color.FromHex("#a8ce76"),
        BorderThickness = new Thickness(1),
    };
    private static readonly StyleBoxFlat InactiveGrowthStageStyle = new()
    {
        BackgroundColor = Color.FromHex("#252a24"),
        BorderColor = Color.FromHex("#4b5548"),
        BorderThickness = new Thickness(1),
    };

    private readonly Dictionary<string, Button> _cultureButtons = [];
    private readonly List<PanelContainer> _growthStageSegments = [];
    private List<FungusMachineInventoryEntry> _inventory = [];
    private string? _pendingCultureId;
    private string? _currentCultureId;
    private float _secondsUntilHarvest;
    private float _harvestProgress;
    private float _harvestDurationSeconds;
    private int _displayedSeconds = -1;
    private int _displayedGrowthStage = -1;
    private bool _countdownActive;

    public event Action<string>? OnGrowRequested;
    public event Action? OnHarvestRequested;

    public FungusMachineMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GrowButton.OnPressed += _ => RequestGrow();
        HarvestButton.OnPressed += _ => OnHarvestRequested?.Invoke();
    }

    public void UpdateState(FungusMachineInterfaceState state)
    {
        var catalogChanged = _inventory.Count != state.Inventory.Count ||
                             !_inventory.Select(entry => entry.Id)
                                 .SequenceEqual(state.Inventory.Select(entry => entry.Id));

        _inventory = state.Inventory;
        _currentCultureId = state.SelectedCultureId;

        if (catalogChanged)
            RebuildCatalog();

        if (_pendingCultureId == null || _inventory.All(entry => entry.Id != _pendingCultureId))
            _pendingCultureId = _currentCultureId ?? _inventory.FirstOrDefault()?.Id;

        UpdateSelectionPanel();
        UpdateCurrentCulture(state);
        UpdateButtonStates();
    }

    private void RebuildCatalog()
    {
        FungusContents.DisposeAllChildren();
        _cultureButtons.Clear();

        var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        foreach (var entry in _inventory)
        {
            if (!_prototypeManager.TryIndex<EntityPrototype>(entry.ProductId, out var productPrototype))
                continue;

            var button = new Button
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                ToggleMode = true,
                MinSize = new Vector2(0, 172),
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
                Margin = new Thickness(6, 8),
            };

            content.AddChild(new TextureRect
            {
                Texture = spriteSystem.GetPrototypeIcon(productPrototype).Default,
                SetSize = new Vector2(96, 96),
                TextureScale = new Vector2(3, 3),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                MouseFilter = MouseFilterMode.Pass,
                ToolTip = Loc.GetString(entry.Description),
            });
            var cultureName = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Center,
                MinHeight = 34,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 6, 0, 0),
            };
            cultureName.SetMessage(Loc.GetString(entry.Name), Color.FromHex("#c5a469"));
            content.AddChild(cultureName);
            button.AddChild(content);

            var cultureId = entry.Id;
            button.OnPressed += _ => SelectCulture(cultureId);
            FungusContents.AddChild(button);
            _cultureButtons.Add(cultureId, button);
        }
    }

    private void SelectCulture(string cultureId)
    {
        _pendingCultureId = cultureId;
        UpdateSelectionPanel();
        UpdateButtonStates();
    }

    private void UpdateSelectionPanel()
    {
        var entry = GetEntry(_pendingCultureId);
        var hasSelection = entry != null;

        SelectedCultureName.Text = hasSelection
            ? Loc.GetString(entry!.Name)
            : Loc.GetString("cult-yogg-fungus-ui-no-selection");
        SelectedCultureDescription.SetMessage(hasSelection
            ? FormatGrowthDetails(entry!)
            : string.Empty);

        var replacesCulture = hasSelection &&
                              _currentCultureId != null &&
                              _currentCultureId != _pendingCultureId;
        ReplaceWarning.Visible = replacesCulture;
        GrowButton.Text = replacesCulture
            ? Loc.GetString("cult-yogg-fungus-ui-replace")
            : Loc.GetString("cult-yogg-fungus-ui-grow");
        GrowButton.Disabled = !hasSelection || _pendingCultureId == _currentCultureId;
    }

    private void UpdateCurrentCulture(FungusMachineInterfaceState state)
    {
        var current = GetEntry(state.SelectedCultureId);
        if (current == null)
        {
            _countdownActive = false;
            CurrentCultureName.Text = Loc.GetString("cult-yogg-fungus-ui-empty");
            CurrentStatus.Text = Loc.GetString("cult-yogg-fungus-ui-select-culture");
            CurrentTiming.Text = string.Empty;
            CurrentYield.Text = string.Empty;
            RebuildGrowthStages(0);
            _harvestProgress = 0;
            _harvestDurationSeconds = 0;
            HarvestButton.Disabled = true;
            return;
        }

        CurrentCultureName.Text = Loc.GetString(current.Name);
        RebuildGrowthStages(current.GrowthStages);
        _harvestProgress = Math.Clamp(state.HarvestProgress, 0, 1);
        var remainingProgress = 1 - _harvestProgress;
        _harvestDurationSeconds = remainingProgress > 0 && state.SecondsUntilHarvest > 0
            ? state.SecondsUntilHarvest / remainingProgress
            : 0;
        UpdateGrowthStages(_harvestProgress, state.HarvestReady);
        CurrentYield.Text = Loc.GetString("cult-yogg-fungus-ui-yield", ("yield", state.Yield));
        HarvestButton.Disabled = !state.HarvestReady;

        if (state.HarvestReady)
        {
            _countdownActive = false;
            CurrentStatus.Text = Loc.GetString("cult-yogg-fungus-ui-ready");
            CurrentTiming.Text = Loc.GetString("cult-yogg-fungus-ui-ready-hint");
            return;
        }

        CurrentStatus.Text = Loc.GetString("cult-yogg-fungus-ui-growing");
        _secondsUntilHarvest = state.SecondsUntilHarvest;
        _displayedSeconds = -1;
        _countdownActive = true;
        UpdateCountdown();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_countdownActive)
            return;

        _secondsUntilHarvest = Math.Max(0, _secondsUntilHarvest - args.DeltaSeconds);
        if (_harvestDurationSeconds > 0)
        {
            _harvestProgress = Math.Min(1, _harvestProgress + args.DeltaSeconds / _harvestDurationSeconds);
            UpdateGrowthStages(_harvestProgress, false);
        }

        UpdateCountdown();
    }

    private void RebuildGrowthStages(int stageCount)
    {
        if (_growthStageSegments.Count == stageCount)
            return;

        GrowthStages.DisposeAllChildren();
        _growthStageSegments.Clear();
        _displayedGrowthStage = -1;

        for (var i = 0; i < stageCount; i++)
        {
            var segment = new PanelContainer
            {
                HorizontalExpand = true,
                Margin = new Thickness(1, 0),
                PanelOverride = InactiveGrowthStageStyle,
            };

            GrowthStages.AddChild(segment);
            _growthStageSegments.Add(segment);
        }
    }

    private void UpdateGrowthStages(float progress, bool harvestReady)
    {
        var activeStages = harvestReady
            ? _growthStageSegments.Count
            : Math.Clamp((int) MathF.Ceiling(progress * _growthStageSegments.Count), 0, _growthStageSegments.Count);

        if (_displayedGrowthStage == activeStages)
            return;

        _displayedGrowthStage = activeStages;
        for (var i = 0; i < _growthStageSegments.Count; i++)
        {
            _growthStageSegments[i].PanelOverride = i < activeStages
                ? ActiveGrowthStageStyle
                : InactiveGrowthStageStyle;
        }
    }

    private void UpdateCountdown()
    {
        var displayedSeconds = Math.Max(0, (int) MathF.Ceiling(_secondsUntilHarvest));
        if (_displayedSeconds == displayedSeconds)
            return;

        _displayedSeconds = displayedSeconds;
        CurrentTiming.Text = Loc.GetString(
            "cult-yogg-fungus-ui-time-left",
            ("time", FormatTime(displayedSeconds)));
    }

    private void UpdateButtonStates()
    {
        foreach (var (id, button) in _cultureButtons)
        {
            button.Pressed = id == _pendingCultureId;
            button.Disabled = id == _currentCultureId;
        }
    }

    private void RequestGrow()
    {
        if (_pendingCultureId == null || _pendingCultureId == _currentCultureId)
            return;

        OnGrowRequested?.Invoke(_pendingCultureId);
    }

    private FungusMachineInventoryEntry? GetEntry(string? id)
    {
        return id == null ? null : _inventory.FirstOrDefault(entry => entry.Id == id);
    }

    private static string FormatTime(int seconds)
    {
        return $"{seconds / 60}:{seconds % 60:00}";
    }

    private static string FormatGrowthDetails(FungusMachineInventoryEntry entry)
    {
        var repeatHarvest = entry.HarvestRepeats
            ? FormatTime(entry.RepeatHarvestSeconds)
            : Loc.GetString("cult-yogg-fungus-ui-no-repeat-harvest");

        return Loc.GetString(
            "cult-yogg-fungus-ui-growth-details",
            ("firstHarvest", FormatTime(entry.FirstHarvestSeconds)),
            ("repeatHarvest", repeatHarvest),
            ("stages", entry.GrowthStages),
            ("maturation", entry.MaturationCycles),
            ("production", entry.ProductionCycles),
            ("yield", entry.Yield));
    }
}
