// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Stylesheets.Palette;
using Content.Shared.SS220.CultYogg.FungusMachine;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.CultYogg.FungusMachine;

[GenerateTypedNameReferences]
public sealed partial class FungusCultureButton : Button
{
    public string CultureId { get; }

    public FungusCultureButton(FungusMachineInventoryEntry entry, Texture texture)
    {
        RobustXamlLoader.Load(this);

        CultureId = entry.Id;
        PlantIcon.Texture = texture;
        PlantIcon.ToolTip = Loc.GetString(entry.Description);
        CultureName.SetMessage(Loc.GetString(entry.Name), Palettes.Gold.Text);
    }
}
