using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GameRules;

/// <summary>
/// Displays a station event's description, conditions and selection status from the admin snapshot.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminEventDetailsWindow : FancyWindow
{
    public AdminEventDetailsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Updates the description, availability and conditions from the latest event snapshot.
    /// </summary>
    public void UpdateEntry(AdminEventTableEntry entry)
    {
        EventName.SetMessage(AdminGameRuleTooltip.GetName(entry.Prototype, entry.Name));
        Description.SetMessage(AdminGameRuleTooltip.GetDescription(entry.Prototype, entry.Description));
        Availability.SetMessage(GetAvailabilityText(entry.Availability));
        Availability.Modulate = entry.Availability == AdminEventAvailability.Available ? Color.White : Color.LightCoral;

        UpdateConditions(entry);
    }

    private void UpdateConditions(AdminEventTableEntry entry)
    {
        WeightValue.SetMessage(Loc.GetString("admin-gamerules-info-weight", ("weight", entry.Weight.ToString("0.###"))));
        OccurrencesValue.SetMessage(entry.Occurrences.ToString());
        PlayersValue.SetMessage(entry.MinimumPlayers.ToString());
        EarliestValue.SetMessage(Loc.GetString("admin-gamerules-info-minutes", ("minutes", entry.EarliestStartMinutes)));
        RepeatValue.SetMessage(Loc.GetString("admin-gamerules-info-minutes", ("minutes", entry.ReoccurrenceDelayMinutes)));
        LimitValue.SetMessage(entry.MaxOccurrences == null
            ? Loc.GetString("admin-gamerules-entry-unlimited")
            : Loc.GetString("admin-gamerules-entry-limit", ("count", entry.MaxOccurrences.Value)));
        RoundEndValue.SetMessage(Loc.GetString(entry.OccursDuringRoundEnd
            ? "admin-gamerules-entry-round-end-allowed"
            : "admin-gamerules-entry-round-end-blocked"));
    }

    /// <summary>
    /// Returns the localized selection status for event details and tooltips.
    /// </summary>
    public static string GetAvailabilityText(AdminEventAvailability availability)
    {
        return Loc.GetString("admin-gamerules-availability", ("availability", availability.ToString()));
    }
}
