using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.GameTicking.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.GameRules;

/// <summary>
/// Searches concrete GameRule prototypes and requests a new rule instance from the server.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminGameRulePickerWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypes = default!;

    private const int AllCategoriesId = -1;

    private List<AdminGameRulePrototypeInfo> _rules = [];
    private string? _selected;
    private bool _canAdd;
    private bool _waiting;
    private ProtoId<GameRuleCategoryPrototype>? _category;
    private List<ProtoId<GameRuleCategoryPrototype>> _categories = [];
    private bool _schedulersOnly;

    public event Action<string>? AddRequested;

    public AdminGameRulePickerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        CategoryFilter.OnItemSelected += args =>
        {
            _category = null;
            if (args.Id != AllCategoriesId)
                _category = _categories[args.Id];

            CategoryFilter.SelectId(args.Id);
            RebuildList();
        };
        Search.OnTextChanged += _ => RebuildList();
        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ => AddSelectedRule();
    }

    private void AddSelectedRule()
    {
        if (!_canAdd || _waiting || _selected == null)
            return;

        _waiting = true;
        Status.SetMessage(Loc.GetString("admin-gamerules-add-pending"));
        RebuildList();
        AddRequested?.Invoke(_selected);
    }

    public void UpdateRules(List<AdminGameRulePrototypeInfo> rules, bool canAdd, bool schedulersOnly)
    {
        if (_schedulersOnly != schedulersOnly)
        {
            _category = null;
            _selected = null;
            Search.Text = string.Empty;
        }
        _schedulersOnly = schedulersOnly;
        _rules = rules;
        _canAdd = canAdd;
        UpdateFilters();
        RebuildList();
        if (!canAdd)
            Close();
    }

    public void HandleResult(bool success)
    {
        _waiting = false;
        RebuildList();
        Status.SetMessage(success ? string.Empty : Loc.GetString("admin-gamerules-add-failed"));
        if (success)
            Close();
    }

    private void UpdateFilters()
    {
        _categories =
        [
            .. _rules.Select(rule => rule.Category).Distinct()
                .OrderByDescending(category => _prototypes.Index(category).Priority)
                .ThenBy(category => category.Id, StringComparer.Ordinal)
        ];
        CategoryFilterBox.Visible = _categories.Count > 1;
        if (_categories.Count <= 1)
            _category = null;

        if (_category != null && !_categories.Contains(_category.Value))
            _category = null;

        CategoryFilter.Clear();
        CategoryFilter.AddItem(Loc.GetString("admin-gamerules-add-all-categories"), AllCategoriesId);
        for (var index = 0; index < _categories.Count; index++)
            CategoryFilter.AddItem(GetCategoryName(_categories[index]), index);
        CategoryFilter.SelectId(_category == null ? AllCategoriesId : _categories.IndexOf(_category.Value));
    }

    private string GetCategoryName(ProtoId<GameRuleCategoryPrototype> category)
    {
        return Loc.GetString(_prototypes.Index(category).Name);
    }

    private void RebuildList()
    {
        var query = Search.Text.Trim();
        List<AdminGameRulePrototypeInfo> matches =
        [
            .. _rules
                .Where(rule => _category == null || rule.Category == _category)
                .Where(rule => rule.Id.Contains(query, StringComparison.OrdinalIgnoreCase)
                    || rule.Name.Contains(query, StringComparison.CurrentCultureIgnoreCase))
                .OrderByDescending(rule => _prototypes.Index(rule.Category).Priority)
                .ThenBy(rule => rule.Category.Id, StringComparer.Ordinal)
                .ThenBy(rule => rule.Id, StringComparer.Ordinal)
        ];
        if (!matches.Any(rule => rule.Id == _selected))
            _selected = null;

        if (_selected == null && !_waiting)
            Status.SetMessage(string.Empty);

        RuleList.RemoveAllChildren();
        var buttons = new ButtonGroup();
        foreach (var group in matches.GroupBy(rule => rule.Category))
        {
            AddGroupHeading(group.Key);
            foreach (var rule in group)
                AddRuleButton(rule, buttons);
        }

        if (matches.Count == 0)
            RuleList.AddChild(new Label { Text = Loc.GetString("admin-gamerules-add-empty") });

        Search.Editable = !_waiting;
        CategoryFilter.Disabled = _waiting;
        ConfirmButton.Disabled = !_canAdd || _waiting || _selected == null;
    }

    private void AddGroupHeading(ProtoId<GameRuleCategoryPrototype> category)
    {
        var heading = new RichTextLabel { Margin = new Thickness(4, 8, 4, 4), Modulate = Color.Gold };
        heading.SetMessage(GetCategoryName(category));
        RuleList.AddChild(heading);
    }

    private void AddRuleButton(AdminGameRulePrototypeInfo rule, ButtonGroup group)
    {
        var button = new Button
        {
            Text = rule.Id,
            ToolTip = AdminGameRuleTooltip.Get(rule, rule.Id),
            ClipText = true,
            TextAlign = Label.AlignMode.Left,
            Group = group,
            Pressed = rule.Id == _selected,
            Disabled = _waiting,
            MinHeight = 28,
        };
        button.OnPressed += _ =>
        {
            _selected = rule.Id;
            Status.SetMessage(Loc.GetString("admin-gamerules-add-selected", ("id", rule.Id)));
            ConfirmButton.Disabled = !_canAdd || _waiting;
        };
        RuleList.AddChild(button);
    }
}
