using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.GameRules;

/// <summary>
/// Displays current rules and their scheduler tables, and offers an authorized rule picker.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminGameRulesControlWindow : FancyWindow
{
    private const int GameRulesTab = 0;
    private const int SchedulersTab = 1;

    private AdminGameRulesControlEuiState _state = new();
    private NetEntity? _selectedScheduler;
    private NetEntity? _selectedGameRule;
    private bool _pickerSchedulersOnly = true;
    private readonly AdminEventDetailsWindow _detailsWindow = new();
    private string? _detailsPrototype;
    private NetEntity? _detailsScheduler;
    private readonly AdminGameRulePickerWindow _rulePicker = new();
    private NetEntity? _addedRule;
    private bool _stoppingRule;
    private float _timerPollRemaining;
    private Dictionary<NetEntity, AdminSchedulerTimerInfo> _timers = [];
    private readonly HashSet<(NetEntity Scheduler, string Table, string Category)> _collapsedCategories = [];
    private readonly HashSet<NetEntity> _expandedHistory = [];

    public event Action<string>? AddRuleRequested;
    public event Action<NetEntity>? StopRuleRequested;
    public event Action<NetEntity>? TimerRefreshRequested;

    public AdminGameRulesControlWindow()
    {
        RobustXamlLoader.Load(this);
        Tabs.SetTabTitle(GameRulesTab, Loc.GetString("admin-gamerules-group-gamerules"));
        Tabs.SetTabTitle(SchedulersTab, Loc.GetString("admin-gamerules-group-schedulers"));
        Tabs.OnTabChanged += _ => _timerPollRemaining = 0;
        OnClose += _detailsWindow.Close;
        OnClose += _rulePicker.Close;
        AddSchedulerButton.OnPressed += _ => OpenPicker(true);
        AddGameRuleButton.OnPressed += _ => OpenPicker(false);
        _rulePicker.AddRequested += id => AddRuleRequested?.Invoke(id);
        StopSchedulerButton.OnPressed += _ => RequestStop(_selectedScheduler);
        StopGameRuleButton.OnPressed += _ => RequestStop(_selectedGameRule);
    }

    private void OpenPicker(bool schedulersOnly)
    {
        if (!_state.CanAddRules)
            return;

        _pickerSchedulersOnly = schedulersOnly;
        UpdatePicker();
        _rulePicker.OpenCentered();
        _rulePicker.MoveToFront();
    }

    private void UpdatePicker()
    {
        _rulePicker.UpdateRules([.. _state.AvailableRules.Where(rule => !_pickerSchedulersOnly || rule.IsScheduler)], _state.CanAddRules, _pickerSchedulersOnly);
    }

    private void RequestStop(NetEntity? entity)
    {
        if (!_state.CanStopRules || _stoppingRule || entity == null)
            return;

        _stoppingRule = true;
        UpdateStopButton();
        ActionStatus.SetMessage(Loc.GetString("admin-gamerules-stop-waiting"));
        ActionStatus.Visible = true;
        StopRuleRequested?.Invoke(entity.Value);
    }

    /// <summary>
    /// Replaces the displayed snapshot while preserving the selected rule when it still exists.
    /// </summary>
    public void UpdateState(AdminGameRulesControlEuiState state)
    {
        _state = state;
        _timers = state.Timers.ToDictionary(timer => timer.Scheduler);
        _collapsedCategories.RemoveWhere(key => !state.Rules.Any(rule => rule.Entity == key.Scheduler));
        AddSchedulerButton.Disabled = !state.CanAddRules;
        AddGameRuleButton.Disabled = !state.CanAddRules;
        UpdatePicker();
        var added = state.Rules.FirstOrDefault(rule => rule.Entity == _addedRule);
        if (added != null)
        {
            if (!_pickerSchedulersOnly || !added.IsScheduler)
            {
                _selectedGameRule = _addedRule;
                Tabs.CurrentTab = GameRulesTab;
            }
            else
            {
                _selectedScheduler = _addedRule;
                Tabs.CurrentTab = SchedulersTab;
            }
            _addedRule = null;
        }
        EventsStatus.Text = Loc.GetString(state.EventsEnabled
            ? "admin-gamerules-enabled"
            : "admin-gamerules-disabled");

        List<AdminGameRuleInfo> schedulers = [.. state.Rules.Where(rule => rule.IsScheduler)];
        var gameRules = state.Rules;
        _selectedScheduler = schedulers.FirstOrDefault(rule => rule.Entity == _selectedScheduler)?.Entity ?? schedulers.FirstOrDefault()?.Entity;
        _selectedGameRule = gameRules.FirstOrDefault(rule => rule.Entity == _selectedGameRule)?.Entity ?? gameRules.FirstOrDefault()?.Entity;
        RebuildRules(SchedulersList, schedulers, _selectedScheduler, entity =>
        {
            _selectedScheduler = entity;
            _timerPollRemaining = 0;
            UpdateTables();
        });
        RebuildRules(GameRulesList, gameRules, _selectedGameRule, entity =>
        {
            _selectedGameRule = entity;
            UpdateStopButton();
        });
        UpdateHistory();
        UpdateTables();
        UpdateDetails();
    }

    private void RebuildRules(BoxContainer list, List<AdminGameRuleInfo> rules, NetEntity? selected, Action<NetEntity> select)
    {
        list.RemoveAllChildren();
        var group = new ButtonGroup();
        foreach (var rule in rules)
        {
            var button = new Button
            {
                Group = group,
                Pressed = rule.Entity == selected,
                HorizontalExpand = true,
                MinHeight = 48,
                ClipText = true,
                TextAlign = Label.AlignMode.Left,
                Text = $"{rule.Prototype} ({rule.Entity})\n{GetStatus(rule.Status)}",
                ToolTip = $"{GetGameRuleTooltip(rule.Prototype)}\n{rule.Prototype} ({rule.Entity})",
            };
            button.OnPressed += _ => select(rule.Entity);
            list.AddChild(button);
        }

        if (rules.Count == 0)
            AddText(list, Loc.GetString("admin-gamerules-no-rules"));
    }

    private void UpdateHistory()
    {
        _expandedHistory.RemoveWhere(entity => !_state.History.Any(entry => entry.Entity == entity));
        HistoryList.RemoveAllChildren();
        foreach (var entry in _state.History)
        {
            var contents = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 6, Margin = new Thickness(8) };
            var card = new PanelContainer { Name = entry.Prototype, StyleClasses = { StyleClass.PanelDark } };
            var heading = new BoxContainer { SeparationOverride = 8 };
            var expanded = _expandedHistory.Contains(entry.Entity);
            var toggle = new Button
            {
                Name = "HistoryToggle",
                Text = $"{(expanded ? "▼" : "▶")} {entry.Prototype} ({entry.Entity})",
                ToolTip = GetGameRuleTooltip(entry.Prototype),
                HorizontalExpand = true,
                ClipText = true,
                TextAlign = Label.AlignMode.Left,
                ToggleMode = true,
                Pressed = expanded,
            };
            heading.AddChild(toggle);
            heading.AddChild(new Label
            {
                Name = "HistoryStatus",
                Text = AdminGameRuleHistoryText.Status(entry.Status),
                Modulate = AdminGameRuleHistoryText.StatusColor(entry.Status),
            });
            contents.AddChild(heading);
            var fields = new TableContainer { Name = "HistoryFields", Columns = 2, HorizontalExpand = true, Visible = expanded };
            toggle.OnToggled += args =>
            {
                fields.Visible = args.Pressed;
                toggle.Text = $"{(args.Pressed ? "▼" : "▶")} {entry.Prototype} ({entry.Entity})";
                if (args.Pressed)
                    _expandedHistory.Add(entry.Entity);
                else
                    _expandedHistory.Remove(entry.Entity);
            };
            AddHistoryField(fields, "admin-gamerules-history-added", AdminGameRuleHistoryText.Time(entry.AddedAt));
            AddHistoryField(fields, "admin-gamerules-history-started", AdminGameRuleHistoryText.Time(entry.StartedAt));
            AddHistoryField(fields, "admin-gamerules-history-ended", AdminGameRuleHistoryText.Time(entry.EndedAt));
            AddHistoryField(fields, "admin-gamerules-history-source", AdminGameRuleHistoryText.Source(entry.Source));
            AddHistoryField(fields, "admin-gamerules-history-reason", AdminGameRuleHistoryText.EndReason(entry));
            contents.AddChild(fields);
            card.AddChild(contents);
            HistoryList.AddChild(card);
        }

        if (_state.History.Count == 0)
            AddText(HistoryList, Loc.GetString("admin-gamerules-history-empty"));
    }

    private static void AddHistoryField(TableContainer table, string key, string value)
    {
        table.AddChild(new Label { Text = Loc.GetString(key), Margin = new Thickness(0, 0, 8, 4) });
        var label = new RichTextLabel { Name = key, HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 4) };
        label.SetMessage(value);
        table.AddChild(label);
    }

    private void UpdateTables()
    {
        UpdateStopButton();
        UpdateTimerLabel();
        EntriesList.RemoveAllChildren();
        var rule = _state.Rules.FirstOrDefault(rule => rule.Entity == _selectedScheduler);
        if (rule == null)
        {
            SelectedSchedulerLabel.SetMessage(string.Empty);
            AddText(EntriesList, Loc.GetString("admin-gamerules-select-rule"));
            return;
        }

        SelectedSchedulerLabel.SetMessage($"{rule.Prototype} ({rule.Entity}) — {GetStatus(rule.Status)}");
        List<AdminEventTableInfo> tables = [.. _state.Tables.Where(table => table.Scheduler == rule.Entity)];
        if (tables.Count == 0)
        {
            AddText(EntriesList, Loc.GetString("admin-gamerules-rule-no-table"));
            return;
        }

        foreach (var table in tables)
        {
            AddText(EntriesList, table.Table.Length == 0 ? Loc.GetString("admin-gamerules-inline-table") : table.Table);
            AddLikelihoodChart(table);
            if (table.Entries.Count == 0)
            {
                AddText(EntriesList, Loc.GetString("admin-gamerules-empty-table"));
                continue;
            }

            AddCategory(table, "admin-gamerules-category-triggered",
                [.. table.Entries.Where(entry => entry.Occurrences > 0)]);
            AddCategory(table, "admin-gamerules-category-waiting",
                [.. table.Entries.Where(entry => entry.Occurrences == 0 && entry.Availability == AdminEventAvailability.Available)]);
            AddCategory(table, "admin-gamerules-category-unavailable",
                [.. table.Entries.Where(entry => entry.Occurrences == 0 && entry.Availability != AdminEventAvailability.Available)]);
        }
    }

    private void AddLikelihoodChart(AdminEventTableInfo table)
    {
        List<AdminEventTableEntry> candidates =
        [
            .. table.Entries
                .Where(entry => entry.Availability == AdminEventAvailability.Available && entry.Weight > 0)
                .OrderByDescending(entry => entry.Weight)
                .ThenBy(entry => entry.Prototype, StringComparer.Ordinal)
        ];
        var chart = new PanelContainer { Name = "LikelihoodPanel", StyleClasses = { StyleClass.PanelDark } };
        var contents = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4, Margin = new Thickness(8) };
        chart.AddChild(contents);
        EntriesList.AddChild(chart);
        AddText(contents, Loc.GetString("admin-gamerules-likelihood-title"));
        if (candidates.Count == 0)
        {
            AddText(contents, Loc.GetString("admin-gamerules-likelihood-empty"));
            return;
        }

        foreach (var entry in candidates.Take(3))
        {
            var row = new BoxContainer { Name = entry.Prototype, SeparationOverride = 8 };
            row.AddChild(new Label { Text = entry.Prototype, ToolTip = GetGameRuleTooltip(entry.Prototype), ClipText = true, HorizontalExpand = true });
            row.AddChild(new ProgressBar
            {
                MinWidth = 100,
                MinHeight = 16,
                VerticalAlignment = VAlignment.Center,
                MaxValue = candidates[0].Weight,
                Value = entry.Weight,
            });
            row.AddChild(new Label
            {
                Text = Loc.GetString("admin-gamerules-likelihood-weight", ("weight", entry.Weight.ToString("0.###"))),
                MinWidth = 80,
            });
            contents.AddChild(row);
        }

        if (candidates.Count > 3)
            AddText(contents, Loc.GetString("admin-gamerules-likelihood-more", ("count", candidates.Count - 3)));

        AddText(contents, Loc.GetString("admin-gamerules-likelihood-hint"));
    }

    /// <summary>
    /// Applies a server timer update without rebuilding lists or losing their scroll position.
    /// </summary>
    public void UpdateTimer(AdminSchedulerTimerInfo timer)
    {
        if (!_state.Rules.Any(rule => rule.Entity == timer.Scheduler))
            return;

        _timers[timer.Scheduler] = timer;
        UpdateTimerLabel();
    }

    private void UpdateTimerLabel()
    {
        NextAttemptLabel.Visible = _selectedScheduler != null;
        if (_selectedScheduler == null)
            return;

        if (!_timers.TryGetValue(_selectedScheduler.Value, out var timer) || timer.Seconds == null)
        {
            NextAttemptLabel.Text = Loc.GetString("admin-gamerules-next-attempt-inactive");
            return;
        }

        var remaining = TimeSpan.FromSeconds(Math.Ceiling(timer.Seconds.Value));
        var time = $"{(int)remaining.TotalMinutes:00}:{remaining.Seconds:00}";
        NextAttemptLabel.Text = Loc.GetString(timer.Paused ? "admin-gamerules-next-attempt-paused" : "admin-gamerules-next-attempt", ("time", time));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!IsOpen || Tabs.CurrentTab != SchedulersTab || _selectedScheduler == null)
            return;

        _timerPollRemaining -= args.DeltaSeconds;
        if (_timerPollRemaining > 0)
            return;

        _timerPollRemaining = 1;
        TimerRefreshRequested?.Invoke(_selectedScheduler.Value);
    }

    private void AddCategory(AdminEventTableInfo table, string title, List<AdminEventTableEntry> entries)
    {
        var key = (table.Scheduler, table.Table, title);
        var contents = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 6 };
        var body = new CollapsibleBody();
        body.AddChild(contents);
        var heading = new CollapsibleHeading(Loc.GetString(title, ("count", entries.Count)))
        {
            Margin = new Thickness(0, 6, 0, 4),
        };
        var section = new Collapsible(heading, body)
        {
            Name = title,
            BodyVisible = !_collapsedCategories.Contains(key),
        };
        heading.OnToggled += args =>
        {
            if (args.Pressed)
                _collapsedCategories.Remove(key);
            else
                _collapsedCategories.Add(key);
        };
        EntriesList.AddChild(section);

        foreach (var entry in entries)
            AddEntry(contents, table, entry);
    }

    private void AddEntry(BoxContainer contents, AdminEventTableInfo table, AdminEventTableEntry entry)
    {
        var row = new BoxContainer { Name = entry.Prototype, SeparationOverride = 8, Margin = new Thickness(8, 4) };
        var card = new PanelContainer { StyleClasses = { StyleClass.PanelDark } };
        card.AddChild(row);
        var label = new RichTextLabel
        {
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Modulate = entry.Availability == AdminEventAvailability.Available ? Color.White : Color.LightCoral,
            ToolTip = $"{GetGameRuleTooltip(entry.Prototype)}\n{AdminEventDetailsWindow.GetAvailabilityText(entry.Availability)}",
        };
        label.SetMessage(entry.Prototype);
        row.AddChild(label);
        var info = new Button
        {
            Text = "i",
            MinSize = new Vector2(28, 28),
            VerticalAlignment = VAlignment.Center,
            ToolTip = $"{Loc.GetString("admin-gamerules-info-button", ("id", entry.Prototype))}\n{GetGameRuleTooltip(entry.Prototype)}",
        };
        info.OnPressed += _ =>
        {
            _detailsPrototype = entry.Prototype;
            _detailsScheduler = table.Scheduler;
            _detailsWindow.UpdateEntry(entry);
            _detailsWindow.OpenCentered();
            _detailsWindow.MoveToFront();
        };
        row.AddChild(info);
        contents.AddChild(card);
    }

    public void HandleAddResult(NetEntity? entity)
    {
        _rulePicker.HandleResult(entity != null);
        if (entity == null)
            return;

        _addedRule = entity;
        UpdateState(_state);
    }

    public void HandleStopResult(bool success)
    {
        _stoppingRule = false;
        ActionStatus.Visible = !success;
        if (!success)
            ActionStatus.SetMessage(Loc.GetString("admin-gamerules-stop-failed"));

        UpdateStopButton();
    }

    private void UpdateStopButton()
    {
        StopSchedulerButton.Disabled = !_state.CanStopRules || _stoppingRule || _selectedScheduler == null;
        StopGameRuleButton.Disabled = !_state.CanStopRules || _stoppingRule || _selectedGameRule == null;
    }

    private void UpdateDetails()
    {
        if (!_detailsWindow.IsOpen)
            return;

        var entry = _state.Tables.Where(table => table.Scheduler == _detailsScheduler)
            .SelectMany(table => table.Entries)
            .FirstOrDefault(entry => entry.Prototype == _detailsPrototype);
        if (entry == null)
        {
            _detailsWindow.Close();
            return;
        }

        _detailsWindow.UpdateEntry(entry);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _detailsWindow.Close();
            _detailsWindow.Dispose();
            _rulePicker.Close();
            _rulePicker.Dispose();
        }

        base.Dispose(disposing);
    }

    private string GetGameRuleTooltip(string prototype)
    {
        return AdminGameRuleTooltip.Get(_state.AvailableRules.FirstOrDefault(rule => rule.Id == prototype), prototype);
    }

    private static string GetStatus(AdminGameRuleStatus status)
    {
        return Loc.GetString(status switch
        {
            AdminGameRuleStatus.Active => "admin-gamerules-active",
            AdminGameRuleStatus.Delayed => "admin-gamerules-delayed",
            _ => "admin-gamerules-pending",
        });
    }

    private static void AddText(BoxContainer container, string text)
    {
        var label = new RichTextLabel { HorizontalExpand = true };
        label.SetMessage(text);
        container.AddChild(label);
    }
}
