using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.PDA;
using Robust.Client.UserInterface.Controls;
using JetBrains.Annotations;

namespace Content.Client.PDA.Ringer
{
    [GenerateTypedNameReferences]
    public sealed partial class RingtoneMenu : DefaultWindow
    {
        public string[] PreviousNoteInputs = new[] { "A", "A", "A", "A", "A", "A" };
        public LineEdit[] RingerNoteInputs = default!;
        private int _ringLen;

        public RingtoneMenu()
        {
            RobustXamlLoader.Load(this);

            RingerNoteInputs = new[] { RingerNote1Input, RingerNote2Input, RingerNote3Input, RingerNote4Input, RingerNote5Input, RingerNote6Input };
            _ringLen = RingerNoteInputs.Length;

            foreach (LineEdit input in RingerNoteInputs)
            {
                input.OnTextChanged += e => AdjustText(input, e.Text);
                input.OnTextEntered += _ => MoveToNext(input);
                input.OnFocusExit += _ => FocusExit(input);
                //input.OnKeyBindDown += OnArrows();
            }

        }
        /*
        private void OnArrows(LineEdit.GUIBoundKeyEventArgs args)
        {

        }*/

        public void FocusExit(LineEdit line)
        {
            string result = "";
            foreach (var c in line.Text)
            {
                if (char.IsLetter(c) || c == '#')
                    result += c;
            }

            line.Text = result;


            int i = Array.IndexOf(RingerNoteInputs, line);

            if (!IsNote(line.Text))
            {
                line.Text = PreviousNoteInputs[i];
                return;
            }
            else
            {
                PreviousNoteInputs[i] = line.Text;
            }
        }

        public void MoveToNext(LineEdit line)
        {
            int i = Array.IndexOf(RingerNoteInputs, line);
            LineEdit ringerNoteInput = RingerNoteInputs[(i + 1) % _ringLen];
            ringerNoteInput.GrabKeyboardFocus();
            ringerNoteInput.CursorPosition = 0;
        }

        public void AdjustText(LineEdit line, string text)
        {
            int cursor = line.CursorPosition - 1;

            if (text == "" || cursor < 0)
                return;

            text = text.ToUpper();

            line.Text = CursorCheck(text, cursor);
        }

        public string CursorCheck(string text, int cursor)
        {
            string cursorString = text[cursor].ToString();

            if (cursorString == "#")
               return text[..(cursor + 1)];

            return text[cursor].ToString();
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            //Prevents the ringtone window from being resized
            return DragMode.Move;
        }

        /// <summary>
        /// Determines whether or not the characters inputed are authorized
        /// </summary>
        public static bool IsNote(string input)
        {
            input = input.Replace("#", "sharp");

            return Enum.TryParse(input, true, out Note _);
        }
    }
}
