using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.PDA;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.PDA.Ringer
{
    [GenerateTypedNameReferences]
    public sealed partial class RingtoneMenu : DefaultWindow
    {
        public string[] PreviousNoteInputs = new[] { "A", "A", "A", "A", "A", "A" };
        public LineEdit[] RingerNoteInputs = default!;

        public RingtoneMenu()
        {
            RobustXamlLoader.Load(this);

            RingerNoteInputs = new[] { RingerNote1Input, RingerNote2Input, RingerNote3Input, RingerNote4Input, RingerNote5Input, RingerNote6Input };

            foreach(LineEdit input in RingerNoteInputs)
            {
                input.OnTextChanged += e => AdjustText(input, e.Text);
            }
        }

        public void AdjustText(LineEdit line, string text)
        {

            if (line.Text == "")
                return;

            foreach (var a in text)
            {
                if (!char.IsLetter(a))
                    text = text.Replace(a.ToString(), "");
            }

            text = text.ToUpper();

            if (line.CursorPosition == line.Text.Length)
                text = text.Remove(0, text.Length - 1);
            else text = text.Remove(1, 1);

            line.Text = text;
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            //Prevents the ringtone window from being resized
            return DragMode.Move;
        }

        /// <summary>
        /// Determines whether or not the characters inputed are authorized
        /// </summary>
        public static bool IsNote(string input)
        {
            input = input.Replace("#", "sharp");

            return Enum.TryParse(input, true, out Note _);
        }
    }
}
