using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.PDA;
using Robust.Client.UserInterface.Controls;
using JetBrains.Annotations;

namespace Content.Client.PDA.Ringer
{
    [GenerateTypedNameReferences]
    public sealed partial class RingtoneMenu : DefaultWindow
    {
        public string[] PreviousNoteInputs = new[] { "A", "A", "A", "A", "A", "A" };
        public LineEdit[] RingerNoteInputs = default!;
        private int _ringLen;

        public RingtoneMenu()
        {
            RobustXamlLoader.Load(this);

            RingerNoteInputs = new[] { RingerNote1Input, RingerNote2Input, RingerNote3Input, RingerNote4Input, RingerNote5Input, RingerNote6Input };
            _ringLen = RingerNoteInputs.Length;

            foreach(LineEdit input in RingerNoteInputs)
            {
                input.OnTextChanged += e => AdjustText(input, e.Text);
                input.OnTextEntered += _ => MoveToNext(input);
                input.OnFocusExit += _ => FocusExit(input);
            }
        }

        public void FocusExit(LineEdit line)
        {
            line.Background
            //line.SetMarkup();
        }

        public void MoveToNext(LineEdit line)
        {
            int i = Array.IndexOf(RingerNoteInputs, line);
            LineEdit ringerNoteInput = RingerNoteInputs[(i + 1) % _ringLen];
            ringerNoteInput.GrabKeyboardFocus();
            ringerNoteInput.CursorPosition = 0;
        }

        public void AdjustText(LineEdit line, string text)
        {

            if (text == "")
                return;

            string result = "";
            foreach (var c in text)
            {
                if (char.IsLetter(c) || c == '#' || c == ' ')
                    result += c;
            }

            result = result.ToUpper();

            if (result.Length <= 2)
            {
                line.Text = result;
                return;
            }

            if (line.CursorPosition == text.Length)
            {
                result = result.Remove(0, 1);
            }
            else result = result.Remove(2, 1);
            line.Text = result;
            MoveToNext(line);
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            //Prevents the ringtone window from being resized
            return DragMode.Move;
        }

        /// <summary>
        /// Determines whether or not the characters inputed are authorized
        /// </summary>
        public static bool IsNote(string input)
        {
            input = input.Replace("#", "sharp");

            return Enum.TryParse(input, true, out Note _);
        }
    }
}
