using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Events;

/// <summary>
/// Searches concrete GameRule prototypes and requests a new rule instance from the server.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminGameRulePickerWindow : FancyWindow
{
    private const int AllEventCategoriesId = -1;

    private List<AdminGameRulePrototypeInfo> _rules = new();
    private string? _selected;
    private bool _canAdd;
    private bool _waiting;
    private AdminStationEventCategory? _eventCategory;

    public event Action<string>? AddRequested;

    public AdminGameRulePickerWindow()
    {
        RobustXamlLoader.Load(this);
        EventCategoryFilter.OnItemSelected += args =>
        {
            _eventCategory = args.Id == AllEventCategoriesId ? null : (AdminStationEventCategory) args.Id;
            EventCategoryFilter.SelectId(args.Id);
            RebuildList();
        };
        Search.OnTextChanged += _ => RebuildList();
        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ => AddSelectedRule();
    }

    private void AddSelectedRule()
    {
        if (!_canAdd || _waiting || _selected == null)
            return;

        _waiting = true;
        Status.SetMessage(Loc.GetString("admin-events-add-pending"));
        RebuildList();
        AddRequested?.Invoke(_selected);
    }

    public void UpdateRules(List<AdminGameRulePrototypeInfo> rules, bool canAdd)
    {
        if (_rules.FirstOrDefault()?.Category != rules.FirstOrDefault()?.Category)
        {
            _eventCategory = null;
            _selected = null;
            Search.Text = string.Empty;
        }
        _rules = rules;
        _canAdd = canAdd;
        UpdateFilters();
        RebuildList();
        if (!canAdd)
            Close();
    }

    public void HandleResult(bool success)
    {
        _waiting = false;
        RebuildList();
        Status.SetMessage(success ? string.Empty : Loc.GetString("admin-events-add-failed"));
        if (success)
            Close();
    }

    private void UpdateFilters()
    {
        var categories = _rules.Where(rule => rule.Category == AdminGameRuleCategory.Events)
            .Select(rule => rule.EventCategory).Distinct().OrderBy(category => category).ToList();
        EventFilterBox.Visible = categories.Count > 1;
        if (categories.Count <= 1)
            _eventCategory = null;

        if (_eventCategory != null && !categories.Contains(_eventCategory.Value))
            _eventCategory = null;

        EventCategoryFilter.Clear();
        EventCategoryFilter.AddItem(Loc.GetString("admin-events-add-all-events"), AllEventCategoriesId);
        foreach (var category in categories)
            EventCategoryFilter.AddItem(AdminGameRuleCategoryText.Get(category), (int) category);
        EventCategoryFilter.SelectId(_eventCategory == null ? AllEventCategoriesId : (int) _eventCategory.Value);
    }

    private void RebuildList()
    {
        var query = Search.Text.Trim();
        var matches = _rules
            .Where(rule => _eventCategory == null || (rule.Category == AdminGameRuleCategory.Events && rule.EventCategory == _eventCategory))
            .Where(rule => rule.Id.Contains(query, StringComparison.OrdinalIgnoreCase)
                || rule.Name.Contains(query, StringComparison.CurrentCultureIgnoreCase))
            .OrderBy(rule => rule.Category)
            .ThenBy(rule => rule.EventCategory)
            .ThenBy(rule => rule.Id, StringComparer.Ordinal)
            .ToList();
        if (!matches.Any(rule => rule.Id == _selected))
            _selected = null;

        if (_selected == null && !_waiting)
            Status.SetMessage(string.Empty);

        RuleList.DisposeAllChildren();
        var buttons = new ButtonGroup();
        foreach (var group in matches.GroupBy(rule => (rule.Category, rule.EventCategory)))
        {
            AddGroupHeading(group.Key.Category, group.Key.EventCategory);
            foreach (var rule in group)
                AddRuleButton(rule, buttons);
        }

        if (matches.Count == 0)
            RuleList.AddChild(new Label { Text = Loc.GetString("admin-events-add-empty") });

        Search.Editable = !_waiting;
        EventCategoryFilter.Disabled = _waiting;
        ConfirmButton.Disabled = !_canAdd || _waiting || _selected == null;
    }

    private void AddGroupHeading(AdminGameRuleCategory category, AdminStationEventCategory eventCategory)
    {
        var title = AdminGameRuleCategoryText.Get(category);
        if (category == AdminGameRuleCategory.Events)
            title += " / " + AdminGameRuleCategoryText.Get(eventCategory);

        var heading = new RichTextLabel { Margin = new Thickness(4, 8, 4, 4), Modulate = Color.Gold };
        heading.SetMessage(title);
        RuleList.AddChild(heading);
    }

    private void AddRuleButton(AdminGameRulePrototypeInfo rule, ButtonGroup group)
    {
        var button = new Button
        {
            Text = rule.Id,
            ToolTip = AdminEventTooltip.Get(rule, rule.Id),
            ClipText = true,
            TextAlign = Label.AlignMode.Left,
            Group = group,
            Pressed = rule.Id == _selected,
            Disabled = _waiting,
            MinHeight = 28,
        };
        button.OnPressed += _ =>
        {
            _selected = rule.Id;
            Status.SetMessage(Loc.GetString("admin-events-add-selected", ("id", rule.Id)));
            ConfirmButton.Disabled = !_canAdd || _waiting;
        };
        RuleList.AddChild(button);
    }
}
