using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Events;

/// <summary>
/// Displays a station event's description, conditions and selection status from the admin snapshot.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminEventDetailsWindow : FancyWindow
{
    public AdminEventDetailsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Updates the description, availability and conditions from the latest event snapshot.
    /// </summary>
    public void UpdateEntry(AdminEventTableEntry entry)
    {
        EventName.SetMessage(AdminEventTooltip.GetName(entry.Prototype, entry.Name));
        Description.SetMessage(AdminEventTooltip.GetDescription(entry.Prototype, entry.Description));
        Availability.SetMessage(GetAvailabilityText(entry.Availability));
        Availability.Modulate = entry.Availability == AdminEventAvailability.Available ? Color.White : Color.LightCoral;

        UpdateConditions(entry);
    }

    private void UpdateConditions(AdminEventTableEntry entry)
    {
        WeightValue.SetMessage(Loc.GetString("admin-events-info-weight", ("weight", entry.Weight)));
        OccurrencesValue.SetMessage(entry.Occurrences.ToString());
        PlayersValue.SetMessage(entry.MinimumPlayers.ToString());
        EarliestValue.SetMessage(Loc.GetString("admin-events-info-minutes", ("minutes", entry.EarliestStartMinutes)));
        RepeatValue.SetMessage(Loc.GetString("admin-events-info-minutes", ("minutes", entry.ReoccurrenceDelayMinutes)));
        LimitValue.SetMessage(entry.MaxOccurrences == null
            ? Loc.GetString("admin-events-entry-unlimited")
            : Loc.GetString("admin-events-entry-limit", ("count", entry.MaxOccurrences.Value)));
        RoundEndValue.SetMessage(Loc.GetString(entry.OccursDuringRoundEnd
            ? "admin-events-entry-round-end-allowed"
            : "admin-events-entry-round-end-blocked"));
    }

    public static string GetAvailabilityText(AdminEventAvailability availability)
    {
        return Loc.GetString(availability switch
        {
            AdminEventAvailability.Available => "admin-events-available",
            AdminEventAvailability.EventsDisabled => "admin-events-unavailable-disabled",
            AdminEventAvailability.SchedulerInactive => "admin-events-unavailable-scheduler",
            _ => "admin-events-unavailable-conditions",
        });
    }
}
