using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared.SS220.WeaponControl;
using Content.Client.Shuttles.UI;

namespace Content.Client.SS220.WeaponControl;

[GenerateTypedNameReferences]
public sealed partial class WeaponControlConsoleWindow : FancyWindow, IComputerWindow<NavInterfaceState>
{
    public WeaponControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);
    }
}
