// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared.SS220.WeaponControl;
using System.Numerics;


namespace Content.Client.SS220.WeaponControl;

[GenerateTypedNameReferences]
public sealed partial class WeaponControlConsoleWindow : FancyWindow, IComputerWindow<WeaponControlBoundUserInterfaceState>
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    public WeaponControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(EntityUid owner, WeaponControlBoundUserInterfaceState cState)
    {
        var coordinates = _entManager.GetCoordinates(cState.NavState.Coordinates);
        WeaponContainer.SetShuttle(coordinates?.EntityId);
        WeaponContainer.SetConsole(owner);
        WeaponContainer.Visible = true;

        WeaponContainer.UpdateState(cState.NavState);
    }
}
