// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using System.Numerics;
using Content.Client.Pinpointer.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Mobs;
using Content.Shared.SS220.CultYogg.CultMiniMap;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client.SS220.CultYogg.CultMiniMap;

[GenerateTypedNameReferences]
public sealed partial class CultMiniMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entities = default!;

    private readonly Dictionary<SpriteSpecifier, Texture> _markerTextures = new();
    private List<CultMiniMapMember> _members = new();
    private readonly Dictionary<NetEntity, Button> _buttons = new();
    private NetEntity _owner;
    private NetEntity? _selected;

    public event Action<EntityCoordinates>? PingRequested;

    public CultMiniMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchLineEdit.OnTextChanged += _ => RefreshMembers();
        NavMap.TrackedEntitySelectedAction += SelectMember;
        NavMap.PingRequestedAction += OnPingRequested;
        PingButton.OnPressed += _ =>
        {
            NavMap.PingMode = !NavMap.PingMode;
            UpdatePingButton();
        };
    }

    public void UpdateState(CultMiniMapState state, NetEntity owner)
    {
        // Keep only the textures used by the latest configuration; SpriteSystem caches the resources.
        _markerTextures.Clear();
        _members = state.Members;
        _owner = owner;

        var grid = _entities.GetEntity(state.Grid);
        if (NavMap.MapUid != grid)
        {
            NavMap.MapUid = grid;
            NavMap.Offset = Vector2.Zero;
            NavMap.ForceNavMapUpdate();
        }

        NavMap.Visible = grid != null;
        NoMapLabel.Visible = grid == null;
        PingButton.Disabled = grid == null;
        if (grid == null)
            NavMap.PingMode = false;
        UpdatePingButton();
        UpdatePings(state.Pings);
        StationName.Text = grid == null ? Loc.GetString("cult-mini-map-no-grid") : state.GridName;
        MemberCount.Text = Loc.GetString("cult-mini-map-count",
            ("count", _members.Count(member => member.Marker.ShowInList)));

        if (!_members.Any(member => member.Entity == _selected && member.Coordinates != null))
            _selected = null;

        RefreshMembers();
    }

    private void OnPingRequested(EntityCoordinates coordinates)
    {
        UpdatePingButton();
        PingRequested?.Invoke(coordinates);
    }

    private void UpdatePingButton()
    {
        PingButton.Text = Loc.GetString(NavMap.PingMode
            ? "cult-mini-map-ping-armed"
            : "cult-mini-map-ping-button");
        if (NavMap.PingMode)
            PingButton.AddStyleClass(StyleClass.Positive);
        else
            PingButton.RemoveStyleClass(StyleClass.Positive);
    }

    private void UpdatePings(IEnumerable<CultMiniMapPing> pings)
    {
        NavMap.Pings.Clear();
        foreach (var ping in pings)
        {
            var coordinates = _entities.GetCoordinates(ping.Coordinates);
            if (!coordinates.IsValid(_entities))
                continue;

            NavMap.Pings[ping.Id] = new CultMiniMapPingBlip(
                ping.Id,
                coordinates,
                GetTexture(ping.Icon),
                ping.Color,
                ping.Scale);
        }
    }

    private void RefreshMembers()
    {
        MembersTable.RemoveAllChildren();
        _buttons.Clear();
        NavMap.TrackedEntities.Clear();
        NavMap.StructureMarkers.Clear();
        NavMap.LocalizedNames.Clear();

        // Map markers are independent of the text filter and menu grouping.
        foreach (var member in _members)
            AddMapMarker(member);

        var visibleMembers = _members.Where(member => member.Marker.ShowInList && MatchesSearch(member)).ToList();
        var self = visibleMembers.FirstOrDefault(member => member.Entity == _owner);
        if (self != null)
            AddMemberSection(self.Marker, new[] { self });

        foreach (var group in visibleMembers
                     .Where(member => member.Entity != _owner)
                     .GroupBy(member => member.Marker.Component))
        {
            AddMemberSection(group.First().Marker, group.OrderBy(member => member.Name));
        }

        EmptyLabel.Visible = _buttons.Count == 0;
        UpdateSelection();
    }

    private bool MatchesSearch(CultMiniMapMember member)
    {
        var role = GetMarkerLabel(member.Marker);
        return member.Name.Contains(SearchLineEdit.Text, StringComparison.CurrentCultureIgnoreCase)
               || role.Contains(SearchLineEdit.Text, StringComparison.CurrentCultureIgnoreCase);
    }

    private void AddMapMarker(CultMiniMapMember member)
    {
        var coordinates = _entities.GetCoordinates(member.Coordinates);
        if (coordinates == null || !NavMap.Visible)
            return;

        var role = GetMarkerLabel(member.Marker);
        if (member.Marker.MarkerType != CultMiniMapMarkerType.Icon)
        {
            NavMap.StructureMarkers[member.Entity] = new CultMiniMapStructureBlip(
                coordinates.Value,
                member.Marker.MarkerType,
                member.Marker.Color,
                member.Rotation);
            return;
        }

        NavMap.TrackedEntities[member.Entity] = new NavMapBlip(
            coordinates.Value,
            GetMarkerTexture(member.Marker),
            member.Marker.Color,
            member.Entity == _selected,
            scale: member.Marker.Scale);
        var details = member.Name + ", " + role;
        if (member.Marker.ShowHealth)
            details += "\n" + GetHealthStatus(member);
        NavMap.LocalizedNames[member.Entity] = details;
    }

    private void AddMemberSection(CultMiniMapMarker marker, IEnumerable<CultMiniMapMember> members)
    {
        var entries = members.ToList();
        if (entries.Count == 0)
            return;

        if (MembersTable.ChildCount > 0)
            MembersTable.AddChild(new Control { SetHeight = 12 });

        var color = marker.Color;
        var header = new BoxContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(10, 0, 4, 3),
        };
        header.AddChild(CreateMarkerIcon(marker, color, 20f));
        header.AddChild(new Label
        {
            Text = Loc.GetString("cult-mini-map-group", ("group", GetMarkerLabel(marker)), ("count", entries.Count)),
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        });
        MembersTable.AddChild(header);

        foreach (var member in entries)
            AddMemberRow(member);
    }

    private void AddMemberRow(CultMiniMapMember member)
    {
        var coordinates = _entities.GetCoordinates(member.Coordinates);
        var healthText = GetHealthText(member);
        var button = new Button
        {
            HorizontalExpand = true,
            Disabled = coordinates == null || !NavMap.Visible,
            ToolTip = member.Name + "\n" + healthText
                + (coordinates == null ? "\n" + Loc.GetString("cult-mini-map-unavailable") : string.Empty),
        };

        var row = new BoxContainer { HorizontalExpand = true };
        row.AddChild(CreateMarkerIcon(member.Marker, member.Marker.Color, 16f));

        var healthIcon = new AnimatedTextureRect
        {
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 6, 0),
            ToolTip = healthText,
            Modulate = member.HealthState == MobState.Invalid ? Color.Gray : Color.White,
        };
        healthIcon.SetFromSpriteSpecifier(new SpriteSpecifier.Rsi(
            new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), GetHealthIconState(member)));
        healthIcon.DisplayRect.TextureScale = new Vector2(2f);
        row.AddChild(healthIcon);

        row.AddChild(new Label
        {
            Text = member.Name,
            HorizontalExpand = true,
            ClipText = true,
        });
        row.AddChild(new Label
        {
            Text = coordinates == null ? Loc.GetString("cult-mini-map-unavailable") : GetHealthStatus(member),
            Margin = new Thickness(6, 0, 0, 0),
        });

        button.AddChild(row);
        button.OnPressed += _ => SelectMember(member.Entity == _selected ? null : member.Entity);
        _buttons.Add(member.Entity, button);
        MembersTable.AddChild(button);
    }

    private TextureRect CreateMarkerIcon(CultMiniMapMarker marker, Color color, float size)
    {
        return new TextureRect
        {
            Texture = GetMarkerTexture(marker),
            SetSize = new Vector2(size),
            CanShrink = true,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Modulate = color,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 6, 0),
        };
    }

    private Texture GetMarkerTexture(CultMiniMapMarker marker)
    {
        return GetTexture(marker.Icon);
    }

    private Texture GetTexture(SpriteSpecifier icon)
    {
        if (_markerTextures.TryGetValue(icon, out var texture))
            return texture;

        texture = _entities.System<SpriteSystem>().Frame0(icon);
        _markerTextures.Add(icon, texture);
        return texture;
    }

    private static string GetMarkerLabel(CultMiniMapMarker marker)
    {
        return marker.Label is { } label ? Loc.GetString(label) : marker.Component;
    }

    private static string GetHealthIconState(CultMiniMapMember member)
    {
        // Use the actual mob state: critical/dead mobs must never look healthy,
        // even if their state was changed independently of damage thresholds.
        if (member.HealthState == MobState.Dead)
            return "dead";
        if (member.HealthState == MobState.Critical)
            return "critical";
        if (member.HealthState != MobState.Alive || member.DamagePercentage is not { } damage)
            return "alive";

        var index = (int) MathF.Round(4f * Math.Clamp(damage, 0f, 1f));
        return "health" + index;
    }

    private static string GetHealthStatus(CultMiniMapMember member)
    {
        return Loc.GetString(member.HealthState switch
        {
            MobState.Alive => "cult-mini-map-health-alive",
            MobState.Critical => "cult-mini-map-health-critical",
            MobState.Dead => "cult-mini-map-health-dead",
            _ => "cult-mini-map-health-unknown",
        });
    }

    private static string GetHealthText(CultMiniMapMember member)
    {
        var status = GetHealthStatus(member);
        if (member.HealthState == MobState.Invalid)
            return status;

        var damage = member.DamagePercentage is { } percentage
            ? Loc.GetString("cult-mini-map-health-damage", ("percent", MathF.Round(percentage * 100f)))
            : Loc.GetString("cult-mini-map-health-no-damage");
        return status + "\n" + damage;
    }

    private static Color GetColor(CultMiniMapMember member)
    {
        return member.Marker.Color;
    }

    private void SelectMember(NetEntity? entity)
    {
        _selected = entity;
        if (entity is { } selected && NavMap.TrackedEntities.TryGetValue(selected, out var blip))
            NavMap.CenterToCoordinates(blip.Coordinates);

        UpdateSelection();
    }

    private void UpdateSelection()
    {
        NavMap.Focus = _selected;
        foreach (var member in _members)
        {
            var selected = member.Entity == _selected;
            if (_buttons.TryGetValue(member.Entity, out var button))
            {
                if (selected)
                    button.AddStyleClass(StyleClass.Positive);
                else
                    button.RemoveStyleClass(StyleClass.Positive);
            }

            if (!NavMap.TrackedEntities.TryGetValue(member.Entity, out var blip))
                continue;

            var color = GetColor(member);
            if (_selected != null && !selected)
                color *= Color.DimGray;

            NavMap.TrackedEntities[member.Entity] = new NavMapBlip(
                blip.Coordinates, blip.Texture, color, selected, blip.Selectable, blip.Scale);
        }
    }
}
