// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using System.Numerics;
using Content.Client.Pinpointer.UI;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.CultYogg.CultMiniMap;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.SS220.CultYogg.CultMiniMap;

[GenerateTypedNameReferences]
public sealed partial class CultMiniMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entities = default!;

    private readonly SpriteSystem _sprites;
    private List<CultMiniMapTrackedEntity> _trackedEntities = new();
    private readonly Dictionary<NetEntity, Button> _buttons = new();
    private NetEntity _owner;
    private NetEntity? _selected;

    public event Action<EntityCoordinates>? PingRequested;

    public CultMiniMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprites = _entities.System<SpriteSystem>();

        SearchLineEdit.OnTextChanged += _ => RefreshMemberList();
        NavMap.TrackedEntitySelectedAction += SelectMember;
        NavMap.PingRequestedAction += OnPingRequested;
        PingButton.OnPressed += _ =>
        {
            NavMap.PingMode = !NavMap.PingMode;
            UpdatePingButton();
        };
    }

    public void UpdateState(CultMiniMapState state, NetEntity owner)
    {
        _trackedEntities = state.TrackedEntities;
        _owner = owner;

        var grid = _entities.GetEntity(state.Grid);
        if (NavMap.MapUid != grid)
        {
            NavMap.MapUid = grid;
            NavMap.Offset = Vector2.Zero;
            NavMap.ForceNavMapUpdate();
        }

        NavMap.Visible = grid != null;
        NoMapLabel.Visible = grid == null;
        PingButton.Disabled = grid == null;
        if (grid == null)
            NavMap.PingMode = false;
        UpdatePingButton();
        UpdatePings(state.Pings);
        StationName.Text = grid == null ? Loc.GetString("cult-mini-map-no-grid") : state.GridName;
        MemberCount.Text = Loc.GetString("cult-mini-map-count",
            ("count", _trackedEntities.Count(entity => entity.Marker.ShowInList)));

        if (!_trackedEntities.Any(entity => entity.Entity == _selected && entity.Coordinates != null))
            _selected = null;

        RefreshMapMarkers();
        RefreshMemberList();
    }

    private void OnPingRequested(EntityCoordinates coordinates)
    {
        UpdatePingButton();
        PingRequested?.Invoke(coordinates);
    }

    private void UpdatePingButton()
    {
        PingButton.Text = Loc.GetString(NavMap.PingMode
            ? "cult-mini-map-ping-armed"
            : "cult-mini-map-ping-button");
        if (NavMap.PingMode)
            PingButton.AddStyleClass(StyleClass.Positive);
        else
            PingButton.RemoveStyleClass(StyleClass.Positive);
    }

    private void SelectMember(NetEntity? entity)
    {
        _selected = entity;
        if (entity is { } selected && NavMap.TrackedEntities.TryGetValue(selected, out var blip))
            NavMap.CenterToCoordinates(blip.Coordinates);

        UpdateSelection();
    }

    private void UpdateSelection()
    {
        NavMap.Focus = _selected;
        foreach (var member in _trackedEntities)
        {
            var selected = member.Entity == _selected;
            if (_buttons.TryGetValue(member.Entity, out var button))
            {
                if (selected)
                    button.AddStyleClass(StyleClass.Positive);
                else
                    button.RemoveStyleClass(StyleClass.Positive);
            }

            if (!NavMap.TrackedEntities.TryGetValue(member.Entity, out var blip))
                continue;

            var color = _selected != null && !selected
                ? member.Marker.Color * Color.DimGray
                : member.Marker.Color;

            NavMap.TrackedEntities[member.Entity] = new NavMapBlip(
                blip.Coordinates, blip.Texture, color, selected, blip.Selectable, blip.Scale);
        }
    }
}
